### PR TITLE
Changes to panel item (esp hover)

### PR DESCRIPTION
**Pull request by meshy**

### CODE REVIEW

**Comment by meshy** [comment]
@peroshi/owners please review. This removes the hoverlay from the items on the homepage.

**Comment by perry** [comment]
I think the main reason for the overlay was to eventually add some sort of content to them, alongside the title. 

But I agree for the time being this is probably the best choice.

**Comment by perry** [comment]
Deployed

**Comment by meshy** [comment]
Thanks :)
Yeah -- if the text comes back then it makes sense

**Pull request merged**
